
before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y build-essential gcc-multilib twine; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo pip install twine; fi

install:
    - travis_wait 40 bash gcc7/build_gcc7.sh

script:
    - bash build.sh

matrix:
  include:
    - os: osx
      osx_image: xcode10
    - os: linux
