os: osx

before_install:
    - pwd
    - ls /usr/local/bin/python*
    - /usr/local/bin/python2.7 -m pip install --user twine

install:
    - bash gcc7/build_gcc7.sh

script:
    - cd gcc7 && /usr/local/bin/python2.7 setup.py --gcc-install-prefix ~/gcc7_install/ bdist_wheel
    - ls dist/*
    - /usr/local/bin/python2.7 -m twine upload dist/*

matrix:
  include:
    - osx_image: xcode7.3
    - osx_image: xcode8.3
    - osx_image: xcode9.4
