
before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y build-essential gcc-multilib; sudo pip install twine six; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo python -m pip install twine; fi

install:
    - travis_wait 40 bash gcc7/build_gcc7.sh

script:
    - bash build.sh

matrix:
  include:
    - os: osx
      osx_image: xcode9.4
    - os: osx
      osx_image: xcode7.3
    - os: linux
