
before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y build-essential gcc-multilib; fi

install:
    - travis_wait 40 bash gcc7/build_gcc7.sh

script:
    - virtualenv vr
    - source vr/bin/activate
    - pip install twine
    - cd gcc7 && python setup.py --gcc-install-prefix ~/gcc7_install/ bdist_wheel
    - ls dist/*
    - python -m twine upload dist/*

matrix:
  include:
    - os: osx
    - os: linux
